using System.Collections;
using System.Collections.Generic;
using Hitbox.Firearms;
using UnityEngine;

[CreateAssetMenu(fileName = "New Firearm Attachment", menuName = "Hitbox/Firearms/FCS/Components/Attachment")]
public class FirearmComponentAttachment : FirearmComponent
{
    #region --- VARIABLES ---


    
    #endregion

    #region --- METHODS ---

    public override FirearmComponentRuntime GetRuntime => new FirearmComponentAttachmentRuntime();

    #endregion
}

// Generated by component node to store runtime data related to current component.
public class FirearmComponentAttachmentRuntime : FirearmComponentRuntime
{
    
}